format_version: 10
pipelines:
  grafana:
    group: create
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-2ae7d73:
        git: https://github.com/devps23/createBucket.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - promethues-stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
          allow_only_on_success: false
        jobs:
          ansible-playbook:
            timeout: 0
            tasks:
            - exec: { command: ansible-playbook, arguments: ["-i","grafana-env.pdevops72.online,","playbook.yml","-e","tools_name=grafana","-e","ansible_user=ec2-user","-e","ansible_password=DevOps321"], run_if: passed }




